# Generated by Django 2.2 on 2019-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('page', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=250)),
                ('user_from', models.CharField(max_length=250)),
                ('user_to', models.CharField(max_length=250)),
                ('date_added', models.CharField(max_length=250)),
                ('date_start', models.CharField(max_length=250)),
                ('date_end', models.CharField(max_length=250)),
                ('date_closed', models.CharField(max_length=250)),
                ('max_time', models.CharField(max_length=250)),
                ('max_money', models.CharField(max_length=250)),
            ],
        ),
    ]
