# Generated by Django 2.2 on 2019-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtasks',
            name='user_from',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='wtasks',
            name='user_to',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='wusers',
            name='email',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='wusers',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
