# Generated by Django 2.2 on 2019-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('mac', models.CharField(max_length=250)),
            ],
        ),
    ]
