# Generated by Django 2.2 on 2019-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('bytes', models.CharField(max_length=250)),
            ],
        ),
    ]
