# Generated by Django 2.2 on 2019-04-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_mtactivity_log_recors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtactivity',
            old_name='log_recors',
            new_name='log_records',
        ),
    ]
