# Generated by Django 2.2 on 2019-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0004_auto_20190417_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('mac', models.CharField(max_length=250)),
            ],
        ),
    ]
