# Generated by Django 2.2 on 2019-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0005_mtusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtactivity',
            name='ip',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtlogin',
            name='ip',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtusers',
            name='ip',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
