# Generated by Django 2.2 on 2019-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0006_auto_20190417_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtlogin',
            name='host_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
