# Generated by Django 2.2 on 2019-04-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0007_mtlogin_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=250)),
                ('host_name', models.CharField(max_length=250)),
                ('log_records', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mtlogin',
            name='host_name',
        ),
    ]
