# Generated by Django 2.2 on 2019-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0008_auto_20190417_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtsession',
            name='mac',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
