# Generated by Django 2.2 on 2019-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0009_mtsession_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=250)),
                ('mac', models.CharField(db_index=True, max_length=250)),
                ('time', models.DateTimeField()),
                ('activity', models.IntegerField(default=0)),
            ],
        ),
    ]
