# Generated by Django 2.2 on 2019-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0010_mtsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
